---
title: ""
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: false
params:
  data: NULL
  summary_table: NULL
  source: "Unknown"
geometry: margin=0.4in
classoption: landscape
header-includes:
  - \usepackage{booktabs}
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(gridExtra)

source("R/data_processing.R", local = TRUE)
source("R/visualization.R",   local = TRUE)

df      <- params$data
summary <- params$summary_table
```

\begin{center}
{\LARGE\bfseries InZone --- Umpire Scorecard} \\[4pt]
{\normalsize Data Source: `r params$source` \quad | \quad Generated: `r Sys.Date()`}
\end{center}

\vspace{-4pt}

```{r three-charts, fig.width=10, fig.height=3.8, fig.align='center', dpi=200}
library(cowplot)

p1 <- plot_overall(df, point_size = 1.5, base = 7) +
  theme(legend.position = "none")
p2 <- plot_false_positives(df, point_size = 1.5, base = 7) +
  theme(legend.position = "none")
p3 <- plot_false_negatives(df, point_size = 1.5, base = 7) +
  theme(legend.position = "none")

# Build a shared legend from the overall map
legend_plot <- plot_overall(df, point_size = 1.5, base = 7) +
  theme(legend.position = "bottom", legend.direction = "horizontal",
        legend.margin = margin(0, 0, 0, 0),
        legend.key.size = unit(0.25, "cm"),
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 7)) +
  guides(colour = guide_legend(nrow = 1))
shared_legend <- cowplot::get_legend(legend_plot)

top_row <- cowplot::plot_grid(p1, p2, p3, ncol = 3, rel_widths = c(1, 1, 1))
cowplot::plot_grid(top_row, shared_legend, ncol = 1, rel_heights = c(1, 0.06))
```

\vspace{-4pt}

\begin{center}
```{r summary-table}
knitr::kable(summary, col.names = c("Metric", "Value"), align = "lr",
             format = "latex", booktabs = TRUE)
```
\end{center}
